### ISSUE TITLE
Getting missing artifact issue while running pom.xml

### ISSUE THREAD

**Issue by RG108** [workwithprashant/karate-reportportal-demo#1]
Hi Prashant,
Thanks for the PR on the integration of Karate with Report Portal. 
I was trying to run the sample project what you created but getting the below missing maven dependencies while running the pom.xml:
1.Missing artifact com.epam.reportportal:agent-java-cucumber:jar:5.0.0-BETA-10
2.Missing artifact com.epam.reportportal:client-java:jar:5.0.1
3.Missing artifact com.epam.reportportal:commons-model:jar:5.2.2

I tried downgrading the dependencies but no luck.
Can you please help me out !

**Comment by workwithprashant** [comment]
I have updated pom.xml with optional repository. I didn't need it since I have my central repository configured to include epam repo.  Please refer to https://github.com/workwithprashant/karate-reportportal-demo/blob/develop/pom.xml

**Comment by RG108** [comment]
Thanks @workwithprashant .  Its working now.
**I tried running the suite and getting new issue like below:**
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building karate-reportportal-demo 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ karate-reportportal-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/cex/git/karate-reportportal-demo/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ karate-reportportal-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ karate-reportportal-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:testCompile (default-testCompile) @ karate-reportportal-demo ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ karate-reportportal-demo ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestRunnerParallel
21:19:17.921 [main] INFO  java.lang.String - +------------------------------------+
21:19:17.927 [main] INFO  java.lang.String - | Starting Functional Test Execution |
21:19:17.927 [main] INFO  java.lang.String - +------------------------------------+
21:19:20.353 [main] INFO  com.epam.reportportal.service.Launch - Rerun: false
21:19:21.721 [rp-io-1] ERROR com.epam.reportportal.service.Launch - [19] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 403
Status message: Forbidden
Error Message: You do not have enough permissions.
Error Type: ACCESS_DENIED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
21:19:21.726 [rp-io-1] ERROR com.epam.reportportal.service.Launch - [19] ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 403
Status message: Forbidden
Error Message: You do not have enough permissions.
Error Type: ACCESS_DENIED

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:85)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Warning: Nashorn engine is planned to be removed from a future JDK release
21:19:23.004 [main] INFO  com.intuit.karate.Runner - waiting for parallel features to complete ...
21:19:23.401 [ForkJoinPool-1-worker-3] WARN  com.intuit.karate - skipping bootstrap configuration: could not find or read file: classpath:karate-config.js
21:19:23.838 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
1 > GET https://jsonplaceholder.typicode.com/users
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Host: jsonplaceholder.typicode.com
1 > User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.1)

21:19:24.654 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - response time in milliseconds: 810.95
1 < 200
1 < Access-Control-Allow-Credentials: true
1 < Age: 27137
1 < CF-Cache-Status: HIT
1 < CF-RAY: 5a35337a8fc2aa5a-SIN
1 < Cache-Control: max-age=43200
1 < Connection: keep-alive
1 < Content-Type: application/json; charset=utf-8
1 < Date: Sun, 14 Jun 2020 15:49:24 GMT
1 < Etag: W/"160d-1eMSsxeJRfnVLRBmYJSbCiJZ1qQ"
1 < Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
1 < Expires: -1
1 < Pragma: no-cache
1 < Server: cloudflare
1 < Set-Cookie: __cfduid=d594df4a713437509bba69528e02c047d1592149764; expires=Tue, 14-Jul-20 15:49:24 GMT; path=/; domain=.typicode.com; HttpOnly; SameSite=Lax
1 < Transfer-Encoding: chunked
1 < Vary: Origin, Accept-Encoding
1 < Via: 1.1 vegur
1 < X-Content-Type-Options: nosniff
1 < X-Powered-By: Express
1 < cf-request-id: 03551e80930000aa5abbb94200000001
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net",
    "company": {
      "name": "Deckow-Crist",
      "catchPhrase": "Proactive didactic contingency",
      "bs": "synergize scalable supply-chains"
    }
  },
  {
    "id": 3,
    "name": "Clementine Bauch",
    "username": "Samantha",
    "email": "Nathan@yesenia.net",
    "address": {
      "street": "Douglas Extension",
      "suite": "Suite 847",
      "city": "McKenziehaven",
      "zipcode": "59590-4157",
      "geo": {
        "lat": "-68.6102",
        "lng": "-47.0653"
      }
    },
    "phone": "1-463-123-4447",
    "website": "ramiro.info",
    "company": {
      "name": "Romaguera-Jacobson",
      "catchPhrase": "Face to face bifurcated interface",
      "bs": "e-enable strategic applications"
    }
  },
  {
    "id": 4,
    "name": "Patricia Lebsack",
    "username": "Karianne",
    "email": "Julianne.OConner@kory.org",
    "address": {
      "street": "Hoeger Mall",
      "suite": "Apt. 692",
      "city": "South Elvis",
      "zipcode": "53919-4257",
      "geo": {
        "lat": "29.4572",
        "lng": "-164.2990"
      }
    },
    "phone": "493-170-9623 x156",
    "website": "kale.biz",
    "company": {
      "name": "Robel-Corkery",
      "catchPhrase": "Multi-tiered zero tolerance productivity",
      "bs": "transition cutting-edge web services"
    }
  },
  {
    "id": 5,
    "name": "Chelsey Dietrich",
    "username": "Kamren",
    "email": "Lucio_Hettinger@annie.ca",
    "address": {
      "street": "Skiles Walks",
      "suite": "Suite 351",
      "city": "Roscoeview",
      "zipcode": "33263",
      "geo": {
        "lat": "-31.8129",
        "lng": "62.5342"
      }
    },
    "phone": "(254)954-1289",
    "website": "demarco.info",
    "company": {
      "name": "Keebler LLC",
      "catchPhrase": "User-centric fault-tolerant solution",
      "bs": "revolutionize end-to-end systems"
    }
  },
  {
    "id": 6,
    "name": "Mrs. Dennis Schulist",
    "username": "Leopoldo_Corkery",
    "email": "Karley_Dach@jasper.info",
    "address": {
      "street": "Norberto Crossing",
      "suite": "Apt. 950",
      "city": "South Christy",
      "zipcode": "23505-1337",
      "geo": {
        "lat": "-71.4197",
        "lng": "71.7478"
      }
    },
    "phone": "1-477-935-8478 x6430",
    "website": "ola.org",
    "company": {
      "name": "Considine-Lockman",
      "catchPhrase": "Synchronised bottom-line interface",
      "bs": "e-enable innovative applications"
    }
  },
  {
    "id": 7,
    "name": "Kurtis Weissnat",
    "username": "Elwyn.Skiles",
    "email": "Telly.Hoeger@billy.biz",
    "address": {
      "street": "Rex Trail",
      "suite": "Suite 280",
      "city": "Howemouth",
      "zipcode": "58804-1099",
      "geo": {
        "lat": "24.8918",
        "lng": "21.8984"
      }
    },
    "phone": "210.067.6132",
    "website": "elvis.io",
    "company": {
      "name": "Johns Group",
      "catchPhrase": "Configurable multimedia task-force",
      "bs": "generate enterprise e-tailers"
    }
  },
  {
    "id": 8,
    "name": "Nicholas Runolfsdottir V",
    "username": "Maxime_Nienow",
    "email": "Sherwood@rosamond.me",
    "address": {
      "street": "Ellsworth Summit",
      "suite": "Suite 729",
      "city": "Aliyaview",
      "zipcode": "45169",
      "geo": {
        "lat": "-14.3990",
        "lng": "-120.7677"
      }
    },
    "phone": "586.493.6943 x140",
    "website": "jacynthe.com",
    "company": {
      "name": "Abernathy Group",
      "catchPhrase": "Implemented secondary concept",
      "bs": "e-enable extensible e-tailers"
    }
  },
  {
    "id": 9,
    "name": "Glenna Reichert",
    "username": "Delphine",
    "email": "Chaim_McDermott@dana.io",
    "address": {
      "street": "Dayna Park",
      "suite": "Suite 449",
      "city": "Bartholomebury",
      "zipcode": "76495-3109",
      "geo": {
        "lat": "24.6463",
        "lng": "-168.8889"
      }
    },
    "phone": "(775)976-6794 x41206",
    "website": "conrad.com",
    "company": {
      "name": "Yost and Sons",
      "catchPhrase": "Switchable contextually-based project",
      "bs": "aggregate real-time technologies"
    }
  },
  {
    "id": 10,
    "name": "Clementina DuBuque",
    "username": "Moriah.Stanton",
    "email": "Rey.Padberg@karina.biz",
    "address": {
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "zipcode": "31428-2261",
      "geo": {
        "lat": "-38.2386",
        "lng": "57.2232"
      }
    },
    "phone": "024-648-3804",
    "website": "ambrose.net",
    "company": {
      "name": "Hoeger LLC",
      "catchPhrase": "Centralized empowering task-force",
      "bs": "target end-to-end models"
    }
  }
]

21:19:24.894 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
2 > GET https://jsonplaceholder.typicode.com/users/1
2 > Accept-Encoding: gzip,deflate
2 > Connection: Keep-Alive
2 > Cookie: __cfduid=d594df4a713437509bba69528e02c047d1592149764
2 > Host: jsonplaceholder.typicode.com
2 > User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.1)

21:19:25.286 [ForkJoinPool-1-worker-3] ERROR com.intuit.karate - javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure, http call failed after 392 milliseconds for URL: https://jsonplaceholder.typicode.com/users/1
21:19:25.289 [ForkJoinPool-1-worker-3] ERROR com.intuit.karate - http request failed: 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
21:19:25.305 [ForkJoinPool-1-worker-3] WARN  com.intuit.karate - skipping bootstrap configuration: could not find or read file: classpath:karate-config.js
21:19:25.312 [ForkJoinPool-1-worker-3] DEBUG com.intuit.karate - request:
1 > GET https://jsonplaceholder.typicode.com/todos
1 > Accept-Encoding: gzip,deflate
1 > Connection: Keep-Alive
1 > Host: jsonplaceholder.typicode.com
1 > User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.1)

21:19:25.626 [ForkJoinPool-1-worker-3] ERROR com.intuit.karate - javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure, http call failed after 314 milliseconds for URL: https://jsonplaceholder.typicode.com/todos
21:19:25.628 [ForkJoinPool-1-worker-3] ERROR com.intuit.karate - http request failed: 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
21:19:27.107 [pool-3-thread-1] INFO  com.intuit.karate.Runner - <<fail>> feature 1 of 1: classpath:features/users.feature
---------------------------------------------------------
feature: classpath:features/users.feature
report: target/surefire-reports/features.users.json
scenarios:  2 | passed:  0 | failed:  2 | time: 2.1843
---------------------------------------------------------

HTML report: (paste into browser to view) | Karate version: 0.9.6.RC3
file:/Users/cex/git/karate-reportportal-demo/target/surefire-reports/karate-summary.html
===================================================================

Karate version: 0.9.6.RC3
======================================================
elapsed:   9.15 | threads:    1 | thread time: 2.18 
features:     1 | ignored:    0 | efficiency: 0.24
scenarios:    2 | passed:     0 | failed: 2
======================================================
failed features:
features.users: users.feature:15 - 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
users.feature:20 - 
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

21:19:27.310 [main] INFO  java.lang.String - Execution completed for FEATURES = 1   and   SCENARIOS = 2
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.029 s - in TestRunnerParallel
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.560 s
[INFO] Finished at: 2020-06-14T21:19:27+05:30
[INFO] Final Memory: 11M/40M
[INFO] ------------------------------------------------------------------------
  
I configured Report Portal on my server and even I changed the reportPortal.prop file still getting the below error:
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 403
S

**Comment by RG108** [comment]
Sorry @workwithprashant  I got this sorted out. With default RP url its working fine. 
I was using other below PR and was stuck with routing the URL under test.
https://github.com/reportportal/agent-java-karate/issues/5
Can you please validate the question asked in the above PR!

**Comment by workwithprashant** [comment]
Please review the https://github.com/workwithprashant/karate-reportportal-demo#pre-requisites as you need to update reportportal.properties with your reportportal instance. You can also use reportportal demo instance with your GitHub credentials.
